config/routes.rb
Rails.application.routes.draw do
  resources :julgamento_criterios
  resources :julgamentos
  resources :grupo_usuarios
  resources :grupo_avaliacaos
  resources :projetos
  resources :criterios
  resources :alternativas

  match 'julgamento_criterio/all' => 'julgamento_criterios#update_all', :as => :julgamento_criterio_update_all, :via => :put
  match 'julgamento/all' => 'julgamentos#update_all', :as => :julgamento_update_all, :via => :put
  match 'projeto/resultado' => 'projetos#resultado', :as => :resultado_projeto, :via => :get

  root 'projetos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
end

app/models/projeto.rb
class Projeto < ApplicationRecord
  has_many :alternativas
  has_many :criterios
  has_many :julgamentos
  has_many :julgamento_criterios
  has_many :prioridade_relativas
end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  load_and_authorize_resource
  before_action :set_projeto, only: [:show, :edit, :update, :destroy]

  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = Projeto.all
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
  end

  # GET /projetos/new
  def new
    @projeto = Projeto.new
  end

  # GET /projetos/1/edit
  def edit
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.new(projeto_params)
    @projeto.user_id = current_user.id
    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Projeto was successfully created.' }
        format.json { render :show, status: :created, location: @projeto }
      else
        format.html { render :new }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    respond_to do |format|
      if @projeto.update(projeto_params)
        format.html { redirect_to @projeto, notice: 'Projeto was successfully updated.' }
        format.json { render :show, status: :ok, location: @projeto }
      else
        format.html { render :edit }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url, notice: 'Projeto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def resultado
    @projeto = Projeto.find(params[:projeto_id])
    @alternativas = @projeto.alternativas.all
    @criterios = @projeto.criterios.all
    @alternativas.each do |a|
      prioridade = 0
      @criterios.each do |c|
        @pr = PrioridadeRelativa.find_by(:alternativa => a.id, :criterio => c.id)
        prioridade = prioridade+(@pr.valor*c.prioridade)
      end
      a.update(:prioridade_global => prioridade)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
      params.require(:projeto).permit(:nome, :descricao)
    end
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/projetos/_form.html.erb
<%= form_for(projeto) do |f| %>
  <% if projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% projeto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :nome, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :descricao %>
    <%= f.text_area :descricao, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/projetos/edit.html.erb
<div class="row">
  <div class="col-md-5">

<h1>Editar Projeto</h1>

<%= render 'form', projeto: @projeto %>

<!-- <%= link_to 'Show', @projeto %> |
<%= link_to 'Back', projetos_path %> -->
  </div>
</div>

app/views/projetos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-md-12">
        <h5>Projetos</h5>
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Descrição</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @projetos.each do |projeto| %>
              <% if can? :read, projeto %>
                <tr>
                  <td><%= projeto.nome %></td>
                  <td><%= projeto.descricao %></td>
                  <td><%= link_to 'Detalhe', projeto, :class => "btn btn-primary" %></td>
                  <td><%= link_to 'Editar', edit_projeto_path(projeto), :class => "btn btn-warning" %></td>
                  <td><%= link_to 'Deletar', projeto, method: :delete, data: { confirm: 'Tem certeza de que quer excluir o projeto?' }, :class => "btn btn-danger" %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

<br>

<%= link_to 'Cadastrar Projeto', new_projeto_path, :class => "btn btn-primary" %>

app/views/projetos/new.html.erb
<h1>New Projeto</h1>

<%= render 'form', projeto: @projeto %>

<%= link_to 'Back', projetos_path %>

app/views/projetos/resultado.html.erb
<h3>Prioridade dos criterios</h3>
<% @criterios = @projeto.criterios%>
<div class="row">
<div class="col-md-6">
  <table class="table table-striped table-bordered table-hover">
    <% @criterios.each do |c|%>
      <tr>
        <td><%= c.nome%></td>
        <td><%= c.prioridade%></td>
      </tr>
    <% end %>
  </table>
</div>
</div>
</br>
<h3>Prioridade Relativa</h3>

<div class="row">
<div class="col-md-6">

    <% @criterios.each do |c|%>
      <table class="table table-striped table-bordered table-hover">
        <caption><h4><%= c.nome%></h4></caption>
        <% @prioridades_relativas = @projeto.prioridade_relativas.where(:criterio_id => c.id) %>
        <% @prioridades_relativas.each do |pr| %>
          <tr>
            <td><%= pr.alternativa.nome %></td>
            <td><%= pr.valor %></td>
          </tr>
        <% end %>
      </table>
    <% end %>

</div>
</div>
<br/>
<h3>Prioridade Global</h3>
<% @alternativas = @projeto.alternativas%>
<div class="row">
  <div class="col-md-6">
    <table class="table table-striped table-bordered table-hover">
      <% @alternativas.each do |p| %>
        <tr>
          <td><%= p.nome %></td>
          <td><%= p.prioridade_global%></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<%= link_to "Voltar", @projeto ,:class => "btn btn-warning"%>

app/views/projetos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-12">
    <div class="panel-group" id="accordion">
      <div class="panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title"><%= @projeto.nome %></h3>
      </div>
      <div class="panel-body">
          <%= @projeto.descricao %>
      </div>
    </div>
    </div>
  </div>
</div>
<hr />
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th colspan="3">Alternativas</th>
        </tr>
      </thead>
    <tbody>
    <% @projeto.alternativas.each do |alternativa| %>
      <tr>
        <td><%= alternativa.nome %></td>
        <td><%= link_to 'Editar', edit_alternativa_path(alternativa, projeto_id: @projeto.id), :class => "btn btn-warning" %></td>
        <td><%= link_to 'Excluir', alternativa, method: :delete, data: { confirm: 'Tem certeza de que quer excluir a alternativa?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
    <tr>
      <th colspan="3"><%= link_to 'Nova Alternativa', new_alternativa_path(projeto_id: @projeto.id), :class => "btn btn-primary" %></th>
    </tr>
    </tbody>
    </table>
  </div>
</div>
<hr />
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th colspan="4">Criterios</th>
        </tr>
      </thead>
      <tbody>
        <% @projeto.criterios.each do |criterio| %>
          <tr>
            <td><%= criterio.nome %></td>
            <td><%= link_to 'Editar', edit_criterio_path(criterio, projeto_id: @projeto.id), :class => "btn btn-warning" %></td>
            <td><%= link_to 'Excluir', criterio, method: :delete, data: { confirm: 'Tem certeza de que quer excluir o critério?' }, :class => "btn btn-danger"  %></td>
            <td><%= link_to 'Sub Critério', new_criterio_path(criterio_id: criterio.id, projeto_id: @projeto.id), :class => "btn btn-primary"  %></td>
          </tr>
        <% end %>
        <tr>
          <th colspan="4"><%= link_to 'Novo Criterio', new_criterio_path(projeto_id: @projeto.id), :class => "btn btn-primary"   %></th>
        </tr>
      </tbody>
    </table>
  </div>
</div>


<br/>
<%= link_to 'Julgamentos', new_julgamento_path(projeto_id: @projeto.id) , :class => "btn btn-primary" %>

<%= link_to 'Julgamentos dos Criterios', new_julgamento_criterio_path(projeto_id: @projeto.id) , :class => "btn btn-primary" %>

<%= link_to 'Resultados', resultado_projeto_path(projeto_id: @projeto.id) , :class => "btn btn-primary" %>