config/routes.rb
Rails.application.routes.draw do
  resources :julgamento_criterios
  resources :julgamentos
  resources :grupo_usuarios
  resources :grupo_avaliacaos
  resources :projetos
  resources :criterios
  resources :alternativas

  match 'julgamento_criterio/all' => 'julgamento_criterios#update_all', :as => :julgamento_criterio_update_all, :via => :put
  match 'julgamento/all' => 'julgamentos#update_all', :as => :julgamento_update_all, :via => :put
  match 'projeto/resultado' => 'projetos#resultado', :as => :resultado_projeto, :via => :get

  root 'projetos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
end

app/models/criterio.rb
class Criterio < ApplicationRecord
  has_many :Julgamentos, :dependent => :delete_all
  has_many :JulgamentoCriterios, foreign_key: "criterio_1_id", :dependent => :delete_all
  has_many :JulgamentoCriterios, foreign_key: "criterio_2_id", :dependent => :delete_all
  has_many :PrioridadeRelativa, :dependent => :delete_all
end

app/controllers/criterios_controller.rb
class CriteriosController < ApplicationController
  before_action :set_criterio, only: [:show, :edit, :update, :destroy]

  # GET /criterios
  # GET /criterios.json
  def index
    @criterios = Criterio.all
  end

  # GET /criterios/1
  # GET /criterios/1.json
  def show
  end

  # GET /criterios/new
  def new
    @criterio = Criterio.new
  end

  # GET /criterios/1/edit
  def edit
  end

  def subcriteros
  end

  # POST /criterios
  # POST /criterios.json
  def create
    @criterio = Criterio.new(criterio_params)

    respond_to do |format|
      if @criterio.save
        format.html { redirect_to @criterio, notice: 'Criterio was successfully created.' }
        format.json { render :show, status: :created, location: @criterio }
      else
        format.html { render :new }
        format.json { render json: @criterio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criterios/1
  # PATCH/PUT /criterios/1.json
  def update
    respond_to do |format|
      if @criterio.update(criterio_params)
        format.html { redirect_to @criterio, notice: 'Criterio was successfully updated.' }
        format.json { render :show, status: :ok, location: @criterio }
      else
        format.html { render :edit }
        format.json { render json: @criterio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criterios/1
  # DELETE /criterios/1.json
  def destroy
    @projeto = Projeto.find(@criterio.projeto_id)
    @criterio.destroy
    respond_to do |format|
      format.html { redirect_to @projeto, notice: 'Criterio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_criterio
      @criterio = Criterio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def criterio_params
      params.require(:criterio).permit(:nome, :codigo, :projeto_id, :criterio_id)
    end

end

app/helpers/criterios_helper.rb
module CriteriosHelper
end

app/views/criterios/_form.html.erb
<div class="row">
  <div class="col-md-5">
<%= form_for(criterio) do |f| %>
  <% if criterio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(criterio.errors.count, "error") %> prohibited this criterio from being saved:</h2>

      <ul>
      <% criterio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :projeto_id, value: params[:projeto_id] %>

  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :nome, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :codigo %>
    <%= f.text_field :codigo, :class => "form-control" %>
  </div>


  <div class="actions">
    <%= f.submit "Salvar", :class => "btn btn-primary" %>
    <%= link_to "Cancelar", Projeto.find(params[:projeto_id]), :class => "btn btn-danger"%>
  </div>
<% end %>
</div>
</div>

app/views/criterios/edit.html.erb
<h1>Editar Critério</h1>

<%= render 'form', criterio: @criterio %>

<!-- <%= link_to 'Show', @criterio %> |
<%= link_to 'Back', criterios_path %> -->

app/views/criterios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Criterios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @criterios.each do |criterio| %>
      <tr>
        <td><%= criterio.nome %></td>
        <td><%= criterio.codigo %></td>
        <td><%= link_to 'Show', criterio %></td>
        <td><%= link_to 'Edit', edit_criterio_path(criterio) %></td>
        <td><%= link_to 'Destroy', criterio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Criterio', new_criterio_path %>

app/views/criterios/new.html.erb
<h1>Cadastrar Criterio</h1>

<%= render 'form', criterio: @criterio %>

<!-- <%= link_to 'Back', criterios_path %> -->

app/views/criterios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @criterio.nome %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @criterio.codigo %>
</p>

<%= link_to 'Editar', edit_criterio_path(@criterio), :class => "btn btn-warning" %>
<%= link_to 'Voltar', Projeto.find(@criterio.projeto_id), :class => "btn btn-primary" %>