config/routes.rb
Rails.application.routes.draw do
  resources :julgamento_criterios
  resources :julgamentos
  resources :grupo_usuarios
  resources :grupo_avaliacaos
  resources :projetos
  resources :criterios
  resources :alternativas

  match 'julgamento_criterio/all' => 'julgamento_criterios#update_all', :as => :julgamento_criterio_update_all, :via => :put
  match 'julgamento/all' => 'julgamentos#update_all', :as => :julgamento_update_all, :via => :put
  match 'projeto/resultado' => 'projetos#resultado', :as => :resultado_projeto, :via => :get

  root 'projetos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
end

app/models/alternativa.rb
class Alternativa < ApplicationRecord
  has_many :Julgamento, foreign_key: "alternativa_1_id", :dependent => :delete_all
  has_many :Julgamento, foreign_key: "alternativa_2_id", :dependent => :delete_all
  has_many :PrioridadeRelativa, :dependent => :delete_all
end

app/controllers/alternativas_controller.rb
class AlternativasController < ApplicationController
  before_action :set_alternativa, only: [:show, :edit, :update, :destroy]

  # GET /alternativas
  # GET /alternativas.json
  def index
    @alternativas = Alternativa.all
  end

  # GET /alternativas/1
  # GET /alternativas/1.json
  def show
  end

  # GET /alternativas/new
  def new
    @alternativa = Alternativa.new
  end

  # GET /alternativas/1/edit
  def edit
  end

  # POST /alternativas
  # POST /alternativas.json
  def create
    @alternativa = Alternativa.new(alternativa_params)

    respond_to do |format|
      if @alternativa.save
        format.html { redirect_to @alternativa, notice: 'Alternativa was successfully created.' }
        format.json { render :show, status: :created, location: @alternativa }
      else
        format.html { render :new }
        format.json { render json: @alternativa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alternativas/1
  # PATCH/PUT /alternativas/1.json
  def update
    respond_to do |format|
      if @alternativa.update(alternativa_params)
        format.html { redirect_to @alternativa, notice: 'Alternativa was successfully updated.' }
        format.json { render :show, status: :ok, location: @alternativa }
      else
        format.html { render :edit }
        format.json { render json: @alternativa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alternativas/1
  # DELETE /alternativas/1.json
  def destroy
    @projeto = Projeto.find(@alternativa.projeto_id)
    @julgamentos = Julgamento.where(:alternativa_id => @alternativa.id)
    @alternativa.destroy
    respond_to do |format|
      format.html { redirect_to @projeto, notice: 'Alternativa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alternativa
      @alternativa = Alternativa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alternativa_params
      params.require(:alternativa).permit(:nome, :codigo, :projeto_id)
    end
end

app/helpers/alternativas_helper.rb
module AlternativasHelper
end

app/views/alternativas/_form.html.erb
<div class="row">
  <div class="col-md-5">
<%= form_for(alternativa) do |f| %>
  <% if alternativa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alternativa.errors.count, "error") %> prohibited this alternativa from being saved:</h2>

      <ul>
      <% alternativa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :projeto_id, value: params[:projeto_id] %>
  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :nome, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :codigo %>
    <%= f.text_field :codigo, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", :class => "btn btn-primary" %>
    <%= link_to "Cancelar",Projeto.find(params[:projeto_id]) ,:class => "btn btn-danger"%>
  </div>
<% end %>
</div>
</div>

app/views/alternativas/edit.html.erb
<h1>Editar Alternativa</h1>

<%= render 'form', alternativa: @alternativa %>

<!-- <%= link_to 'Show', @alternativa %> |
<%= link_to 'Back', alternativas_path %> -->

app/views/alternativas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alternativas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alternativas.each do |alternativa| %>
      <tr>
        <td><%= alternativa.nome %></td>
        <td><%= alternativa.codigo %></td>
        <td><%= link_to 'Show', alternativa %></td>
        <td><%= link_to 'Edit', edit_alternativa_path(alternativa) %></td>
        <td><%= link_to 'Destroy', alternativa, method: :destroy, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alternativa', new_alternativa_path %>

app/views/alternativas/new.html.erb
<h1>Cadastrar Alternativa</h1>

<%= render 'form', alternativa: @alternativa %>

<!-- <%= link_to 'Voltar', @alternativa.projeto_id, :class => "btn btn-primary" %> -->

app/views/alternativas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @alternativa.nome %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @alternativa.codigo %>
</p>

<%= link_to 'Editar', edit_alternativa_path(@alternativa, projeto_id: @alternativa.projeto_id), :class => "btn btn-warning" %>
<%= link_to 'Voltar', Projeto.find(@alternativa.projeto_id), :class => "btn btn-primary" %>