config/routes.rb
Rails.application.routes.draw do
  resources :julgamento_criterios
  resources :julgamentos
  resources :grupo_usuarios
  resources :grupo_avaliacaos
  resources :projetos
  resources :criterios
  resources :alternativas

  match 'julgamento_criterio/all' => 'julgamento_criterios#update_all', :as => :julgamento_criterio_update_all, :via => :put
  match 'julgamento/all' => 'julgamentos#update_all', :as => :julgamento_update_all, :via => :put
  match 'projeto/resultado' => 'projetos#resultado', :as => :resultado_projeto, :via => :get

  root 'projetos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
end

app/models/julgamento_criterio.rb
class JulgamentoCriterio < ApplicationRecord
  belongs_to :projeto
  belongs_to :criterio_1, class_name: "Criterio", foreign_key: "criterio_1_id"
  belongs_to :criterio_2, class_name: "Criterio", foreign_key: "criterio_2_id"
end

app/controllers/julgamento_criterios_controller.rb
class JulgamentoCriteriosController < ApplicationController
  before_action :set_julgamento_criterio, only: [:show, :edit, :update, :destroy]

  # GET /julgamento_criterios
  # GET /julgamento_criterios.json
  def index
    @julgamento_criterios = JulgamentoCriterio.all
  end

  # GET /julgamento_criterios/1
  # GET /julgamento_criterios/1.json
  def show
  end

  # GET /julgamento_criterios/new
  def new
    @projeto = Projeto.find(params[:projeto_id])

    @criterios1 = @projeto.criterios.all
    @criterios2 = @projeto.criterios.all

    @criterios1.each do |c1|
      @criterios2.each do |c2|

          if JulgamentoCriterio.find_by(:projeto_id => @projeto.id, :criterio_1 => c1.id, :criterio_2 => c2.id) == nil
            @julgamento_criterio = JulgamentoCriterio.new
            @julgamento_criterio.projeto_id = @projeto.id
            @julgamento_criterio.criterio_1_id = c1.id
            @julgamento_criterio.criterio_2_id = c2.id
            @julgamento_criterio.save
          end
      end
    end
    @julgamento_criterios = JulgamentoCriterio.where(:projeto_id => @projeto.id)
  end

  def update_all
    JulgamentoCriterio.update(params[:j].keys, params[:j].values)
    prioridade_relativa
    redirect_to new_julgamento_criterio_path(:projeto_id => params[:projeto_id])
  end

  # GET /julgamento_criterios/1/edit
  def edit
  end

  # POST /julgamento_criterios
  # POST /julgamento_criterios.json
  def create
    @julgamento_criterio = JulgamentoCriterio.new(julgamento_criterio_params)

    respond_to do |format|
      if @julgamento_criterio.save
        format.html { redirect_to @julgamento_criterio, notice: 'Julgamento criterio was successfully created.' }
        format.json { render :show, status: :created, location: @julgamento_criterio }
      else
        format.html { render :new }
        format.json { render json: @julgamento_criterio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /julgamento_criterios/1
  # PATCH/PUT /julgamento_criterios/1.json
  def update
    respond_to do |format|
      if @julgamento_criterio.update(julgamento_criterio_params)
        format.html { redirect_to @julgamento_criterio, notice: 'Julgamento criterio was successfully updated.' }
        format.json { render :show, status: :ok, location: @julgamento_criterio }
      else
        format.html { render :edit }
        format.json { render json: @julgamento_criterio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /julgamento_criterios/1
  # DELETE /julgamento_criterios/1.json
  def destroy
    @julgamento_criterio.destroy
    respond_to do |format|
      format.html { redirect_to julgamento_criterios_url, notice: 'Julgamento criterio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_julgamento_criterio
      @julgamento_criterio = JulgamentoCriterio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def julgamento_criterio_params
      params.require(:julgamento_criterio).permit(:projeto_id, :criterio_1_id, :criterio_2_id, :valor)
    end

    def prioridade_relativa
      @criterios = Criterio.where(:projeto_id => params[:projeto_id])

      @criterios.each do |c1|

          @julgamentos1 = JulgamentoCriterio.where(:projeto_id => params[:projeto_id], :criterio_1 => c1.id)

          total = 0
          @julgamentos1.each do |j|
            @julgamentos2 = JulgamentoCriterio.where(:projeto_id => params[:projeto_id], :criterio_2 => j.criterio_2_id)
            total = total+j.valor/@julgamentos2.sum(:valor)
          end

          c1.update(:prioridade => (total/@julgamentos1.size))

      end

    end


end

app/helpers/julgamento_criterios_helper.rb
module JulgamentoCriteriosHelper
end

app/views/julgamento_criterios/_form.html.erb
<%= form_for :julgamento_criterio, :url => julgamento_criterio_update_all_path(:projeto_id => @projeto.id), :html => { :method => :put } do %>

  <% opcoes = [["1",1.0],["2",2.0],["3",3.0],["4",4.0],["5",5.0],["6",6.0],["7",7.0],["8",8.0],["9",9.0],["1/2",0.5],["1/3",0.333],["1/4",0.25],["1/5",0.20],["1/6",0.166],["1/7",0.142],["1/8",0.125],["1/9",0.111]] %>
  <% @criterios1 = @projeto.criterios %>
  <% @criterios2 = @projeto.criterios %>
  <br/>
    <div class="row">
    <div class="col-md-8">
      <table class="table table-striped table-bordered table-hover">
        <tr>
          <th></th>
          <% @criterios1.each do |c1| %>
            <th><%= c1.nome %></th>
          <% end %>
        </tr>
        <% @criterios1.each do |c1| %>
          <tr>
            <th><%= c1.nome %></th>
            <% @criterios2.each do |c2| %>
              <% @jc = @julgamento_criterios.find_by(:criterio_1_id => c1.id, :criterio_2_id => c2.id) %>
              <%= fields_for "j[]", @jc do |f| %>
                <td><%= f.select :valor, opcoes,{}, :onchange => "set_value(this)", :id => '1_'+c1.id.to_s+'_'+c2.id.to_s %></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <br/>
  <%= submit_tag "Salvar", :class => "btn btn-primary"%>
  <%= link_to "Voltar",Projeto.find(params[:projeto_id]) ,:class => "btn btn-warning"%>

<% end %>

app/views/julgamento_criterios/edit.html.erb
<h1>Editing Julgamento Criterio</h1>

<%= render 'form', julgamento_criterio: @julgamento_criterio %>

<%= link_to 'Show', @julgamento_criterio %> |
<%= link_to 'Back', julgamento_criterios_path %>

app/views/julgamento_criterios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Julgamento Criterios</h1>

<table>
  <thead>
    <tr>
      <th>Projeto</th>
      <th>Criterio 1</th>
      <th>Criterio 2</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @julgamento_criterios.each do |julgamento_criterio| %>
      <tr>
        <td><%= julgamento_criterio.projeto %></td>
        <td><%= julgamento_criterio.criterio_1 %></td>
        <td><%= julgamento_criterio.criterio_2 %></td>
        <td><%= julgamento_criterio.valor %></td>
        <td><%= link_to 'Show', julgamento_criterio %></td>
        <td><%= link_to 'Edit', edit_julgamento_criterio_path(julgamento_criterio) %></td>
        <td><%= link_to 'Destroy', julgamento_criterio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Julgamento Criterio', new_julgamento_criterio_path %>

app/views/julgamento_criterios/new.html.erb
<h1>Julgamento dos Criterios</h1>

<%= render 'form', julgamento_criterio: @julgamento_criterio %>

<!-- <%= link_to 'Back', julgamento_criterios_path %> -->

app/views/julgamento_criterios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Projeto:</strong>
  <%= @julgamento_criterio.projeto %>
</p>

<p>
  <strong>Criterio 1:</strong>
  <%= @julgamento_criterio.criterio_1 %>
</p>

<p>
  <strong>Criterio 2:</strong>
  <%= @julgamento_criterio.criterio_2 %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @julgamento_criterio.valor %>
</p>

<%= link_to 'Edit', edit_julgamento_criterio_path(@julgamento_criterio) %> |
<%= link_to 'Back', julgamento_criterios_path %>